### ISSUE TITLE
[SUGGESTION] Redacted

### ISSUE THREAD

**Issue by Krystool** [Krystool/supreme#5]
Username: GlossyJamesred

Suggestion 1: [REDACTED] members do not show up on the member list on the top right corner. And [REDACTED] and certain MTF taskforces are able to classify their names.
Suggestion 2: So basically when you look at them, you don’t see their name but you see [CLASSIFIED] or [REDACTED] for redacted.

**Comment by Krystool** [comment]
My thoughts on the suggestion:

Very good idea that needs to be expanded, modified or reworked to better implement it in game. Going to work on it.

**Comment by Pair-O-Ducks** [comment]
Suggestion: 323. the main thing i want which is possible since it isn't stated is the ability to pass the skull from one person to another. Kind of like passing the torch. SCP-323 would be one of the only SCP that is controlled by a player. The first person to put on the skull will control it until the host is terminated. The SCP would be fast, have high attack, but have low defense. What i can basically do is engage a mashing mini-game. if the skull user(which i am going to call 1) overpowers the other person, it will perform an instant kill. At this point, 1 can choose if it wants to transfer the skull to the target it just killed. If it does,  it will basically rip it's own head off and place the skull on the new target. 1 still controls SCP-323 but it now has a different body. switching bodies raises your attack.

What i believe should be able to happen is as it takes more host, it is allowed access to more areas. Once it is powerful enough, it can set off the warhead.
One way to achieve this is if it inherits the keycard of the person.
The second possible way would be if it got stronger every body 1 took over until it was powerful enough.

Getting power to enter the warhead room should be possible yet challenging.

Back to the minigame. If the target overpowers 1, it will stun it for 12 seconds and will allow for easy damage.

My biggest concern is how this SCP could not be too OP.
323 was never mentioned to be able to take it's head off but i  the file is loose enough and enough unexplained habits to have this be a possibility.

**Comment by Pair-O-Ducks** [comment]
My thoughts on the suggestion:

Though this makes sense, it is still possible to open up the player menu and see who they are. Would it be possible to perhaps use alt accounts for [REDACTED]? This was a method used in one of the groups i was previously in.

**Comment by Krystool** [comment]
^

**Comment by PokarOriginal** [comment]
We can make a rule where if you info breach you can be demoted/terminated or kicked out of the foundation depending on the seriousness.

**Comment by Krystool** [comment]
> We can make a rule where if you info breach you can be demoted/terminated or kicked out of the foundation depending on the seriousness.

Of course.

**Comment by PokarOriginal** [comment]
Like if we make alts its abit bothersome.

**Comment by Krystool** [comment]
Yeah.

Else I could make them in "cloak"

**Comment by Pair-O-Ducks** [comment]
> Like if we make alts its abit bothersome.

You'd be surprised how well it works. You simply need to set up a few accounts and have them join. It isn't really that hard. Perhaps you can make the users set up the accounts themselves. The way it works. For example, use ISD_3(for ISD) and then a password sent to you by a HR. The HR checks the password by logging into it and then will accept the request to join. Of course, i am saying this with the fact that my ISD O5 created a bot that would send you your account and password.

**Comment by PokarOriginal** [comment]
Let’s say like you are on ISD and there is a riot and you want to get on MTF to help.You have to use atleast 3-5 mins to switch over to your main and get on MTF.So it’s really bothersome and time consuming.

**Comment by Pair-O-Ducks** [comment]
> Let’s say like you are on ISD and there is a riot and you want to get on MTF to help.You have to use atleast 3-5 mins to switch over to your main and get on MTF.So it’s really bothersome and time consuming.

That makes sense and i have gotten into those experiences before. Of course,  i assume [REDACTED] has their own job during a riot  so it shouldn't be frequent. It is an inconvenience for attempting to do so but   that's what you're accepting when you would log onto ISD.

Also, does this SCPF ACTUALLY use the MTF team during riots and breaches? That really makes me happy as that pissed me off as a HR SD to have some MTF kick me off the line to go into a booth.

**Comment by PokarOriginal** [comment]
Only RRT has a role to play in a riot, IA and ISD don’t.

And yes MTF does do something, or if they don’t  I will do something about it provided I get O5 for MTF.

**Comment by PokarOriginal** [comment]
And btw SD doesn’t deal with containment breaches.

**Comment by Krystool** [comment]
> And btw SD doesn’t deal with containment breaches.

Yeah, SD usually doesn't deal with theses.

**Comment by Veylisha** [comment]
> 
> 
> Only RRT has a role to play in a riot, IA and ISD don’t.
> 
> And yes MTF does do something, or if they don’t I will do something about it provided I get O5 for MTF.

GOC is the Main one for these.

**Comment by Pair-O-Ducks** [comment]
I am aware.
